services:
  - type: static_site
    name: qvscl-accelerator-frontend
    repo: https://github.com/rajeshqvscl/accelerator
    branch: main
    buildCommand: ""
    publishDir: frontend
    routes:
      - type: rewrite
        source: /assets/*
        destination: /assets/
      - type: rewrite
        source: /src/*
        destination: /src/
      - type: rewrite
        source: /*
        destination: /index.html
